name: Deploy to QA

on:
  push:
    branches:
      - release

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy build to QA server
        run: |
          sshpass -p "${{ secrets.QA_SERVER_PASSWORD }}" scp -P ${{ secrets.QA_SERVER_PORT }} -o StrictHostKeyChecking=no -r dist/ecomarket-app-frontend/* ${{ secrets.QA_SERVER_USER }}@${{ secrets.QA_SERVER_HOST }}:/path/to/qa/html

      - name: Run script on QA server
        run: |
          sshpass -p "${{ secrets.QA_SERVER_PASSWORD }}" ssh -p ${{ secrets.QA_SERVER_PORT }} -o StrictHostKeyChecking=no ${{ secrets.QA_SERVER_USER }}@${{ secrets.QA_SERVER_HOST }} "
          echo 'Deployment to QA successful!'
          "
