name: Deploy to QA

on:
  push:
    branches:
      - release

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration production --optimization=false
        continue-on-error: true

      - name: Create Dockerfile for Angular App
        run: |
          echo 'FROM nginx:alpine' > Dockerfile
          echo 'COPY dist/ecomarket-app-frontend /usr/share/nginx/html' >> Dockerfile
          echo 'EXPOSE 80' >> Dockerfile

      - name: Build Docker Image
        run: docker build -t ecomarket-app-frontend:qa .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag ecomarket-app-frontend:qa ${{ secrets.DOCKERHUB_USERNAME }}/ecomarket-app-frontend:qa

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecomarket-app-frontend:qa

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run Deployment Script on QA Server
        run: |
          sshpass -p "${{ secrets.QA_SERVER_PASSWORD }}" ssh -p ${{ secrets.QA_SERVER_PORT }} -o StrictHostKeyChecking=no ${{ secrets.QA_SERVER_USER }}@${{ secrets.QA_SERVER_HOST }} "/home/estudiante/ecomarket-app-backend-springboot/scripts/QA/deploy_docker_image-ecomarket-app-frontend-qa.sh"
